version: '3'
services:
  mess1:
    build: ./mess1
  mess2:
    build: ./mess2
  mess3:
    build: ./mess3
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
      - mess1
      - mess2
      - mess3

#docker-compose up --build --scale mess1=3 --scale mess2=3 --scale mess3=3